### ISSUE TITLE
Kindly make it available for Google Chrome.

### ISSUE THREAD

**Issue by rajhanschinmay** [kustodian/extended-statusbar#40]
It is useful add-on.
Would be more than happy to have one for Google Chrome.
Thank you.

**Comment by gemmaweirs** [comment]
I +1 this. There isn't any alternative Chrome extension that's as simple and lightweight as this one as far as I can see. It would be awesome if you could create a Chrome version that works with the existing floating status bar.

**Comment by kustodian** [comment]
I'm sorry, but there are no plans to write this extension for Chrome.
