### ISSUE TITLE
Show specific HTTP HEADER

### ISSUE THREAD

**Issue by extreme-dh** [kustodian/extended-statusbar#41]
I need a simple feature which allows me to display a specific HTTP header value from response headers.
I would like to enter the name of this header in plugins options. If this header is sent in the web page response, it shows up in an extra statusbar field.
Could you add such a feature?

**Comment by adoxa** [comment]
Have you tried other add-ons? Something like [Header Spy](https://addons.mozilla.org/en-US/firefox/addon/header-spy/) sounds like what you want.

**Comment by extreme-dh** [comment]
Yes, this idea is inspired by Header Spy, but I don't think its working with newest FF versions.
At least for me it doesn't.
I can't find other add-on working this way.

**Comment by adoxa** [comment]
It appears to work fine for me (41.0.2), although it doesn't show up on Customize (so it's stuck on the right). I'm using Status-4-Evar, if that makes a difference (Add-on Bar & ESB are hidden).

**Comment by extreme-dh** [comment]
Man, you're great! With Status-4-Evar everything works perfect together!
