### ISSUE TITLE
Incompatible with e10s  - "aBrowser.contentDocument is null"

### ISSUE THREAD

**Issue by Dook1** [kustodian/extended-statusbar#45]
Incompatible with e10s  - "aBrowser.contentDocument is null"

**Comment by TriMoon** [comment]
Why don't you just fix your code to check for existence?
eg, change https://github.com/kustodian/extended-statusbar/blame/master/chrome/content/extendedstatusbar.js#L663
See: https://github.com/kustodian/extended-statusbar/commit/aac18742b78f1c7f2db4e3e51b1f51c5f2d325a8#commitcomment-21980938

**Comment by adoxa** [comment]
Done (using yet another method :)).

**Comment by TriMoon** [comment]
> @adoxa
 Done (using yet another method :)).

Unfortunately IMHO https://github.com/kustodian/extended-statusbar/commit/bdf84e202b645f64246fb67412462dd4023eb397 won't fix it properly because it will introduce another bug...
Reading the code that follows shows it will check for not null, undefined == ! Null

**Comment by adoxa** [comment]
According to the console, undefined does equal null.
