### ISSUE TITLE
Extended Statusbar 2.1  - bug in Pale Moon - status bar disabled on new tab load

### ISSUE THREAD

**Issue by Gordon-Dry** [kustodian/extended-statusbar#52]
I started posting about this issue here:
https://forum.palemoon.org/viewtopic.php?f=3&t=21883

In short words:
A fresh loaded tab got no status bar.
As soon as the tab is toggled by CTRL+TAB the status bar reappears.

As soon as I revert to 2.0.2 the issue is gone.
(I had to download the .zip, unpack it, pack it again without the main folder and rename the .zip to .xpi to be able to install it)

**Comment by Gordon-Dry** [comment]
So, as it works with 2.0.2, that older version got "another issue" which is also cosmetic - some UI elements don't obey the theme colors' settings.
But for now I can live with that.
Better than a (temporarily) missing status bar.

**Comment by adoxa** [comment]
I've released 2.1.1, which fixes it (I hope). If this works for you I'll update the add-on.

**Comment by Gordon-Dry** [comment]
Looks good for now - I will test it for a day and report back.

Happy easter.

**Comment by Gordon-Dry** [comment]
22 hours later... all okay.
