### ISSUE TITLE
No longer works in Pale Moon 29

### ISSUE THREAD

**Issue by jobbautista9** [kustodian/extended-statusbar#53]
Starting in Pale Moon 29, the extension no longer shows any additional information on the status bar, like the image count.

**Comment by mozo78** [comment]
I can confirm - no longer working on Pale Moon 29.

**Comment by wolfbeast** [comment]
Culprit:
``` Javascript
var isPostAustralis = Components.classes["@mozilla.org/xpcom/version-comparator;1"].getService(Components.interfaces.nsIVersionComparator)
.compare(Components.classes["@mozilla.org/xre/app-info;1"].getService(Components.interfaces.nsIXULAppInfo).version, "29.0") >= 0;
```

**Comment by mozo78** [comment]
Thank you very much JustOff!
When it will be in a downloadable release?

**Comment by JustOff** [comment]
As usual, after the author of the extension verifies that the fix is working correctly and accepts the pull request, you can ask him to release a new version if he has not done so by then.

**Comment by adoxa** [comment]
Updated version now available from add-ons (thanks JustOff!).

**Comment by mozo78** [comment]
Thank you very much!

**Comment by JustOff** [comment]
@adoxa, thank you for supporting Pale Moon!
