### ISSUE TITLE
[Question][enhancement] customization of font in userChrome.css?

### ISSUE THREAD

**Issue by Corin-EU** [kustodian/extended-statusbar#56]
palemoon v31.2.0

extended statusbus v2.1.2 (2022-07-17)

In userChrome.css, is it possible to customize the font  (family, size, style etc) as it is with the other "bar" components eg menubar, urlbar?

I have tried amongst other things

           extensions.extendedstatusbar > *
           {
            font-family:                   Lucida Sans               !important;
            font-size:                     12pt                            !important;
            font-style:                    bold                            !important;
          }

but the font never changes.

If I go to "about:config" and look for entries for extendedstatusbar I see numerous lines for different properties but nothing related to font.

Is the font hard coded and cannot be changed?

If this is the case, then please consider allowing it to be change from userChrome.css at least, if not also adding the options to the extended-statusbar preferences window dialog.

**Comment by adoxa** [comment]
Select `Style > Use your own style` and add the CSS there.

**Comment by Corin-EU** [comment]
Thank you for your guidance.  I did not realize that you could enter actual CSS text customization there because the text entry widgets contain something like dots and dashes when I open the dialog window and I thought that it was some pattern for the layout.   Upon actually clicking on the text entry box, it does expand as an empty box to enter text it.

So the specific item to change is actually the "ESB Widget" (and not the t¨oolbar" as I first thought)

Putting into this box

                font-family: Lucida Sans;
                font-size: 12pt;
                font-weight: bold;

(not forgetting the semi-colons for each entry) does change the style appropriately.

Thank you!
